variables:
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.x'

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'

  
  jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
      displayName: 'Install dependencies'
    

    - script: |
        python3 -m pip list
      displayName: 'List installed packages'

    - script: |
        python3 -m venv test
        . test/bin/activate &&
        python3 -m pip install -r requirements.txt &&
        python3 -m pylint *.py
      displayName: 'Activate virtual environment and run tests'


  # - job: UnitTesting
  #   displayName: 'Run Unit Tests'
  #   steps:
  #   - script: |
  #       pip install pytest pytest-azurepipelines
  #       pytest *.py
  #     displayName: 'Run Pytest'

  # - job: PackageDockerImage
  #   displayName: 'Package Docker Image'
  #   steps:
  #   - script: |
  #       docker buildx build -t alexplayer15/elastic-app .'                    
  #       docker tag alexplayer15/elastic-app:latest alexplayer15/elastic-app:test'
  #       docker push alexplayer15/elastic-app:test'
  #     displayName: 'Build and Push Docker Image'