variables:
  -group: KeyVault
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.x'
  IMAGE_TAG: latest
  LOGIN_SERVER: elasticcontainerregistry.azurecr.io
  REPOSITORY: test/alexplayer15/elastic-app

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: 'Deploy Stage'
  
  jobs:
        
  - job: DeployContainerToWebApps
    displayName: 'Deploy Container to Web Apps'
    steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'elasticConnection'
            KeyVaultName: 'kv-elastic-alp-uks'
            SecretsFilter: '*'
            RunAsPreJob: true
        - script: |
              echo "********"
              echo "$(DBURL)"
              echo "$(dockerusername)"
              echo "********"
              echo "********"

        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: 'elasticConnection'
            appName: 'ElasticAppProject'
            resourceGroupName: 'rg-alexp'
            slotName: 'production'
            containers: '$(LOGIN_SERVER)/$(REPOSITORY):$(IMAGE_TAG)'
            appSettings: 
                    -SQLALCHEMY_DATABASE_URI "$(DBURL)"
                    -WEBSITES_CONTAINER_START_TIME_LIMIT:1500
                    -PORT 80
                    -WEBSITES_PORT 80
            