variables:
  -group: KeyVault
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.x'
  IMAGE_TAG: test

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: 'Deploy Stage'
  
  jobs:
        
  - job: DeployContainerToWebApps
    displayName: 'Deploy Container to Web Apps'
    steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'elasticConnection'
            KeyVaultName: 'kv-elastic-alp-uks'
            SecretsFilter: '*'
            RunAsPreJob: true
        - script: |
              echo "********"
              echo "$(DBURL)"
              echo "$(dockerusername)"
              echo "********"
              echo "********"

        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: 'elasticConnection'
            appName: 'ElasticAppProject'
            deployToSlotOrASE: true
            resourceGroupName: 'rg-alexp'
            slotName: 'production'
            containers: 'alexplayer15/elastic-app:$(IMAGE_TAG)'
            appSettings: 
                    -SQLALCHEMY_DATABASE_URI "$(DBURL)"
                    -WEBSITES_PORT 80
                    -Port 80
            