trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'Build Stage'
  
  jobs:
  - job: AzureLogin
    displayName: 'Login to Azure'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'elasticConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az login'
